package com.spyglass.connect.minecraft

import com.spyglass.connect.model.ContainerInfo
import com.spyglass.connect.model.ItemStack
import net.querz.nbt.tag.CompoundTag
import net.querz.nbt.tag.ListTag
import java.io.File

/**
 * Scan Minecraft world for containers (chests, barrels, shulker boxes, etc.)
 * and extract their inventories.
 *
 * Port of minecolony-manager/parser/storage_parser.py container scanning logic.
 */
object ChestScanner {

    /** Block entity IDs that are storage containers. */
    private val CONTAINER_TYPES = setOf(
        "minecraft:chest",
        "minecraft:trapped_chest",
        "minecraft:barrel",
        "minecraft:shulker_box",
        "minecraft:hopper",
        "minecraft:dropper",
        "minecraft:dispenser",
        "minecraft:brewing_stand",
        "minecraft:furnace",
        "minecraft:blast_furnace",
        "minecraft:smoker",
    )

    /**
     * Scan all containers in a world across all dimensions.
     * Returns list of ContainerInfo with items.
     */
    fun scanWorld(worldDir: File): List<ContainerInfo> {
        val containers = mutableListOf<ContainerInfo>()
        for (dimension in listOf("overworld", "the_nether", "the_end")) {
            containers.addAll(scanDimension(worldDir, dimension))
        }
        return containers
    }

    /** Scan all containers in a single dimension. */
    fun scanDimension(worldDir: File, dimension: String): List<ContainerInfo> {
        val regionFiles = AnvilReader.regionFiles(worldDir, dimension)
        val containers = mutableListOf<ContainerInfo>()

        for (regionFile in regionFiles) {
            val chunks = AnvilReader.readRegionChunks(regionFile)
            for (chunk in chunks) {
                val blockEntities = AnvilReader.extractBlockEntities(chunk) ?: continue
                for (i in 0 until blockEntities.size()) {
                    val be = blockEntities[i]
                    val container = parseContainer(be, dimension) ?: continue
                    containers.add(container)
                }
            }
        }

        return containers
    }

    /** Parse a block entity into ContainerInfo, or null if not a container. */
    private fun parseContainer(blockEntity: CompoundTag, dimension: String): ContainerInfo? {
        val id = NbtHelper.string(blockEntity, "id")
        if (id !in CONTAINER_TYPES) return null

        // Skip loot table containers (not yet generated by the game)
        if (blockEntity.containsKey("LootTable")) return null

        val x = NbtHelper.int(blockEntity, "x")
        val y = NbtHelper.int(blockEntity, "y")
        val z = NbtHelper.int(blockEntity, "z")
        val customName = parseCustomName(blockEntity)
        val items = parseItems(blockEntity)

        // Skip empty containers
        if (items.isEmpty()) return null

        return ContainerInfo(
            type = id.removePrefix("minecraft:"),
            x = x, y = y, z = z,
            dimension = dimension,
            customName = customName,
            items = items,
        )
    }

    /**
     * Parse custom name from block entity.
     * Minecraft stores custom names as JSON chat components: {"text":"My Chest"}
     */
    private fun parseCustomName(blockEntity: CompoundTag): String? {
        val raw = NbtHelper.string(blockEntity, "CustomName")
        if (raw.isBlank()) return null
        // Try parsing JSON chat component
        if (raw.startsWith("{")) {
            return try {
                val textMatch = Regex(""""text"\s*:\s*"([^"]*?)"""").find(raw)
                textMatch?.groupValues?.get(1)?.ifBlank { null }
            } catch (_: Exception) {
                raw
            }
        }
        return raw
    }

    /** Parse Items list from a container block entity. */
    @Suppress("UNCHECKED_CAST")
    private fun parseItems(blockEntity: CompoundTag): List<ItemStack> {
        val itemList = blockEntity.get("Items") as? ListTag<CompoundTag> ?: return emptyList()
        return (0 until itemList.size()).mapNotNull { i ->
            val item = itemList[i]
            val id = NbtHelper.string(item, "id").removePrefix("minecraft:")
            if (id.isBlank()) return@mapNotNull null
            // 1.21+ uses lowercase "count" (IntTag); older uses "Count" (ByteTag)
            val count = maxOf(NbtHelper.int(item, "Count", 0), NbtHelper.int(item, "count", 0))
                .coerceAtLeast(1)
            val slot = NbtHelper.int(item, "Slot", -1)
            ItemStack(id = id, count = count, slot = slot)
        }
    }
}
